version: '2'

services:
    db:
        image: mongo:latest
        ports:
            - 27017:27017
        volumes:
            - "../database/mongo:/var/lib/mongodb"
        command: --storageEngine=wiredTiger
    redis:
        image: redis:alpine
        ports:
            - 6379:6379
    php:
        build: php7-fpm
        ports:
            - 9000:9000
        links:
            - db:mysqldb
            - redis
        volumes:
            - .:/var/www/symfony
    nginx:
        build: nginx
        ports:
            - 80:80
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./app/logs/:/var/log/nginx
    elk:
        image: willdurand/elk
        ports:
            - 81:80
        volumes:
            - ./docker/elk/logstash:/etc/logstash
            - ./docker/elk/logstash/patterns:/opt/logstash/patterns
        volumes_from:
            - php
            - nginx
